.\"     Title: mkinitcpio
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 11/14/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "MKINITCPIO" "5" "11/14/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mkinitcpio - Create an initial ramdisk environment
.SH "SYNOPSIS"
mkinitcpio [\fIOPTIONS\fR]
.sp
.SH "DESCRIPTION"
Creates an initial ramdisk environment for booting the linux kernel\. The initial ramdisk is in essence a very small environment (early userspace) which loads various kernel modules and sets up necessary things before handing over control to init\. This makes it possible to have, for example, encrypted root filesystems and root filesystems on a software RAID array\. mkinitcpio allows for easy extension with custom hooks, has autodetection at runtime, and many other features\.
.sp
.SH "OPTIONS"
.PP
\fB\-c\fR \fIconfig\fR
.RS 4
Use
\fIconfig\fR
file to generate the ramdisk\. Default: /etc/mkinitcpio\.conf
.RE
.PP
\fB\-k\fR \fIkernelversion\fR
.RS 4
Use
\fIkernelversion\fR\. Default is the current running kernel\.
.RE
.PP
\fB\-s\fR \fIfilelist\fR
.RS 4
Saves a list of all the files in the initial ramdisk in
\fIfilelist\fR\. Default: no; This means the filelist will not be retained if this option isn\'t specified\. Useful for debugging purposes\.
.RE
.PP
\fB\-b\fR \fIbasedir\fR
.RS 4
Use
\fIbasedir\fR
as a starting point for gathering information about the currently running system\. Default: /\.
.RE
.PP
\fB\-g\fR \fIfilename\fR
.RS 4
Generate a CPIO image as
\fIfilename\fR\. Default: no; this means nothing will be written to the filesystem unless this option is specified\.
.RE
.PP
\fB\-a\fR \fIfilelist\fR
.RS 4
Append to an existing
\fIfilelist\fR\. Default no\.
.RE
.PP
\fB\-p\fR \fIpreset\fR
.RS 4
Build initial ramdisk according to specified
\fIpreset\fR\. Presets are found in /etc/mkinitcpio\.d
.RE
.PP
\fB\-m\fR \fImessage\fR
.RS 4
Print
\fImessage\fR
before passing control to kinit\.
.RE
.PP
\fB\-v\fR
.RS 4
Verbose output\. Outputs more information about what\'s happening during creation of the ramdisk\.
.RE
.PP
\fB\-M\fR
.RS 4
Display modules found via autodetection\. mkinitcpio will automatically try to determine which kernel modules are needed to start your computer\. This option lists which modules were detected\.
.RE
.PP
\fB\-L\fR
.RS 4
List all available hooks\.
.RE
.PP
\fB\-H\fR \fIhookname\fR
.RS 4
Output help for hookname
\fIhookname\fR
.RE
.PP
\fB\-h\fR
.RS 4
Output a short overview of available command\-line switches\.
.RE
.SH "ABOUT HOOKS"
A hook is a script that executes in the initial ramdisk\. The order and which scripts are executed is found in the \fBHOOKS\fR=() array in the mkinitcpio configuration file\. A hook will, for example, set up the udev device filesystem, load IDE modules, etc\&...
.sp
.SH "ABOUT PRESETS"
A preset is a pre\-defined definition on how to create an initial ramdisk\. Instead of specifying the configuration file and which output file, every time you generate a new intial ramdisk, you define a preset and use the \-p switch to generate an initial ramdisk according to your preset\. Presets are located in /etc/mkinitcpio\.d
.sp
.SH "FILES"
.PP
\fI/etc/mkinitcpio\.conf\fR
.RS 4
Default configuration file for mkinitcpio\.
.RE
.PP
\fI/etc/mkinitcpio\.d\fR
.RS 4
Folder containing mkinitcpio presets\.
.RE
.PP
\fI/lib/initcpio\fR
.RS 4
Files related to creating an initial ramdisk\.
.RE
.SH "EXAMPLES"
.PP
\fBmkinitcpio\fR
.RS 4
Perform a
\fIdry\-run\fR\. This will generate an initial ramdisk but will not write anything\. Use \-g to create the real image\.
.RE
.PP
\fBmkinitcpio \-p kernel26\fR
.RS 4
Create an initial ramdisk based on the
\fIkernel26\fR
preset\.
.RE
.SH "TIPS"
Don\'t let the bed bugs bite!
.sp
.SH "SEE ALSO"
A more thorough article on configuring mkinitcpio: <http://wiki\.archlinux\.org/index\.php/Configuring_mkinitcpio>
.sp
initrd(4)
.sp
.SH "BUGS"
Upon writing this manpage, there were no noticeable bugs present\. Please visit <http://bugs\.archlinux\.org/> for an up to date list\.
.sp
.SH "AUTHORS"
mkinitcpio created by the Arch Linux Developer community\.
.PP
Manpage written by:
.RS 4
.sp
.RS 4
\h'-04'\(bu\h'+03'Glenn
\fIRedShift\fR
Matthys <glenn@opengate\.be>
.RE
.RE
.PP
Manpage contributions by:
.RS 4
.sp
.RS 4
\h'-04'\(bu\h'+03'Jens
\fIbyte\fR
Adam <j_adam@web\.de>
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Geir
\fIgejr\fR
Vaagland
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Joerie
\fIThralas\fR
de Gram <j\.de\.gram@gmail\.com>
.RE
.RE
.SH "VERSION INFORMATION"
Manpage written for mkinitcpio 0\.5\.17
.sp
.SH "COPYRIGHT"
Copyright (c) Arch Linux
.sp
