#!/usr/bin/ash

run_hook() {
    if [ -e /consolefont.psfu ]; then
        msg -n ":: Loading console font..."
        setfont -C /dev/console /consolefont.psfu
        msg "done."
    elif [ -e /consolefont.psf ]; then
        msg -n ":: Loading console font..."
        setfont -C /dev/console /consolefont.psf
        msg "done."
    else
        msg "No consolefont found despite added hook."
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
