#!/usr/bin/ash
# SPDX-License-Identifier: GPL-2.0-only

run_hook() {
    if [ -e /consolefont.psfu ]; then
        msg -n ":: Loading console font..."
        # Supported in ash
        # shellcheck disable=SC3036
        echo -en "a\010 \010"
        setfont -C /dev/console /consolefont.psfu
        msg "done."
    elif [ -e /consolefont.psf ]; then
        msg -n ":: Loading console font..."
        # Supported in ash
        # shellcheck disable=SC3036
        echo -en "a\010 \010"
        setfont -C /dev/console /consolefont.psf
        msg "done."
    else
        msg "No consolefont found despite added hook."
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
