#!/usr/bin/ash

run_earlyhook() {
    local quiet
    if command -v '@TMPFILES_PATH@' >/dev/null 2>&1; then
        kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
        '@TMPFILES_PATH@' --prefix=/dev --create --boot
    fi
    quiet="$(getarg quiet)"
    if [ "${quiet}" = "y" ]; then
        '@UDEVD_PATH@' --daemon --resolve-names=never >/dev/null 2>&1
    else
        '@UDEVD_PATH@' --daemon --resolve-names=never
    fi
    # used externally by poll_device()
    # shellcheck disable=SC2034
    udevd_running=1
}

run_hook() {
    msg ":: Triggering uevents..."
    udevadm trigger --action=add --type=subsystems
    udevadm trigger --action=add --type=devices
    udevadm settle
}

run_cleanuphook() {
    udevadm control --exit
    udevadm info --cleanup-db
}

# vim: set ft=sh ts=4 sw=4 et:
