#!/bin/bash

build() {
    if (( fs_autodetect_failed )); then
        MODULES=$(all_modules '/kernel/fs' | grep -v "nls")
    else
        MODULES=$(checked_modules '/kernel/fs' | grep -v "nls")
    fi
}

help() {
    cat <<HELPEOF
This hook adds filesystems modules to the image. If you would like to minimize
the modules installed in the image, add the autodetect hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
