#!/bin/bash

build() {
    MODULES=$(checked_modules "/drivers/firewire/")

    [[ $MODULES ]] && MODULES+=" firewire-sbp2? sd_mod? sr_mod?"
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a firewire root device.  Detection
will take place at runtime. To minimize the modules in the image, add the
autodetect hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
