#!/bin/bash

build() {
  add_file /etc/machine-id
  add_file /etc/hostname
}

help() {
  cat <<HELPEOF
This hook installs host-specific configuration files into the initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
