#!/bin/bash

build() {
    MODULES="$(checked_modules "/ide/" | grep -v "legacy")"

    [[ $MODULES ]] && MODULES+=" ide-gd_mod?"
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for an ide root device, using the old ide
subsystem.  Detection will take place at runtime. To minimize the modules in
the image, add the autodetect hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
