#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
    add_checked_modules -f '(_cs|sl811_hcd|isp116x_hcd)' '/usb/host'
    add_module 'usbhid'
    map add_checked_modules '/hid/hid' '/input/(serio|keyboard)'
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for keyboard devices. As a side-effect
modules for some non-keyboard input devices might also be added, but this should
not be relied on. Detection will take place at runtime. To minimize the modules
in the image, add the autodetect hook prior to this hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
