#!/bin/bash

build() {

    # subshell to avoid namespace pollution
    (
        . "$BASEDIR/etc/rc.conf"
        if [[ $KEYMAP ]]; then
            if [[ $LOCALE = *[Uu][Tt][Ff]-8 ]]; then
                touch "$BUILDROOT/keymap.utf8"
                uc=-u
            fi
            /bin/loadkeys -q $uc $KEYMAP -b > "$BUILDROOT/keymap.bin"
        fi
    )

    (( $? == 0 )) && SCRIPT=keymap
}

help() {
    cat <<HELPEOF
This hook loads keymap(s) specified in rc.conf during early userspace.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
