#!/bin/bash

build() {
    if add_checked_modules '/mmc'; then
        add_module 'tifm_7xx1'
        add_module 'mmc_block'
    fi
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a mmc root device. Detection will
take place at runtime. To minimize the modules in the image, add the autodetect
hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
