#!/bin/bash

build() {
  add_full_dir /etc/modprobe.d
  add_full_dir /usr/lib/modprobe.d
}

help() {
  cat <<HELPEOF
This hook installs modprobe configuration files from /etc/modprobe.d and
/usr/lib/modprobe.d.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
