#!/bin/bash

build() {
    for filter in 'ata/pata_*' 'ata/ata_generic' 'ata/ata_piix'; do
        MODULES+=" $(checked_modules "$filter")"
    done

    [[ $MODULES ]] && MODULES+=" sd_mod?"
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a pata (ide) root device, using the
new libata subsystem. Detection will take place at runtime. To minimize the
modules in the image, add the autodetect hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
