#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
    add_runscript
}

help() {
    cat <<HELPEOF
This hook initializes support for resuming from disk using swsusp.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
