#!/bin/bash

build() {
    local mod

    map add_module 'overlay'

    map add_udev_rule \
        '10-dm.rules' \
        '13-dm-disk.rules' \
        '95-dm-notify.rules' \
	'/usr/lib/initcpio/udev/11-dm-initramfs.rules'

    map add_systemd_unit 'systemd-volatile-root.service'

    # Add systemd verity-related binaries
    map add_binary '/usr/lib/systemd/systemd-volatile-root'
}

help() {
    cat <<HELPEOF
This hook sets up systemd-volatile in the initramfs environment.

Ensure your kernel command line contains valid parameters for it.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
