#!/bin/bash

build() {
    local veritytab

    map add_module 'dm-verity' 'sha256' 'sha512'

    map add_udev_rule \
        '10-dm.rules' \
        '13-dm-disk.rules' \
        '95-dm-notify.rules'

    map add_systemd_unit 'veritysetup-pre.target' \
        'veritysetup.target' \
        'systemd-veritysetup@.service'

    # Add systemd verity-related binaries
    map add_binary '/usr/lib/systemd/system-generators/systemd-veritysetup-generator' \
        '/usr/lib/systemd/systemd-veritysetup'

    # Add veritysetup binary from cryptsetup package
    add_binary '/usr/bin/veritysetup'

    # Add veritytab if present
    if [[ -f /etc/veritytab.initramfs ]]; then
        add_file '/etc/veritytab.initramfs' '/etc/veritytab' 600
        warning '/etc/veritytab.initramfs is deprecated. Merge it into /etc/veritytab and add a x-initrd.attach option to the devices that need to be set up in the initramfs stage.'
    elif [[ -f /etc/veritytab ]]; then
        if veritytab="$(awk '!/^\s*($|#)/ && $5 ~ /x-initrd\.attach/' /etc/veritytab 2>/dev/null)" && [[ -n "$veritytab" ]]; then
            printf '%s\n' "$veritytab" | add_file - '/etc/veritytab' 600
        fi
    fi
}

help() {
    cat <<HELPEOF
This hook sets up dm-verity in the initramfs environment.

Ensure your kernel command line contains valid parameters for dm-verity.
If /etc/veritytab contains lines with x-initrd.attach in the fifth field, those
lines will be added to /etc/veritytab in the initramfs. See veritytab(5) for
details.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
