#!/bin/bash

build() {
    add_binary cp
    add_binary lsblk
    add_binary findmnt
    add_binary umount
    add_file "/usr/lib/initcpio/shutdown" "/shutdown" 755

    add_runscript
}

help() {
    cat <<HELPEOF
This hook copies the contents of the initramfs into /run/initramfs for reuse
on shutdown. This is needed when you have /usr mounted on a separate partition.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
