#!/bin/bash

build() {
    map add_binary \
        '@UDEVD_PATH@' \
        '/usr/bin/udevadm' \
        '/usr/lib/udev/ata_id' \
        '/usr/lib/udev/scsi_id' \
        '/usr/lib/libkmod.so.2'

    # meson-templated path
    # shellcheck disable=SC2157
    if [[ -n '@TMPFILES_PATH@' ]]; then
        add_binary '@TMPFILES_PATH@'
    fi

    map add_udev_rule \
        '50-udev-default.rules' \
        '60-persistent-storage.rules' \
        '64-btrfs.rules' \
        '80-drivers.rules'

    add_runscript
}

help() {
    cat <<HELPEOF
This hook adds the udev daemon to the initramfs, allowing for dynamic loading
of modules and reliable detection of the root device via tags (e.g. UUID or
LABEL). Do not remove this hook unless you are using the systemd hook, or you
know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
