#!/bin/bash

build() {
    local module=

    MODULES="$(checked_modules "/usb/host" | grep -ve "_cs" -e "sl811_hcd" -e "isp116x_hcd")"

    if [[ $MODULES ]]; then
        MODULES+=" usb_storage? sd_mod? sr_mod?"
        MODULES+=" $(checked_modules "drivers/usb/storage/ums-*")"
    fi
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for an usb root device.  Detection will
take place at runtime. To minimize the modules in the image, add the autodetect
hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
